### PR TITLE
December main update

### LINKED ISSUE #108: RegEx is blocking DNS queries without TLD, i.e. local queries
At least on Adguard Home, the following RegEx prevents clients from looking up local hosts by using only their hostname:
```
! For TVs that try to connect to several garbled letter combinations
/^[a-z]{7,15}$/
```

This prevents e.g. lookups of "NAS" or "printer" whereas "NAS.mydomain.TLD" or "printer.local" would work.

Could that RegEx be removed or limited (e.g. to only catch GarbledSomethingDOTanydomainDOTanyTLD ?) My RegEx skills are pretty basic but something like adding "\\." at the end perhaps?

### LINKED ISSUE #109: Invalid domains
When adding the list to Gravity, the following error message appears

[i] Target: https://perflyst.github.io/PiHoleBlocklist/SmartTV-AGH.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 209 domains, 204 domains invalid!
      Sample of invalid domains:
      - ||smartclip.com^
      - ||smartclip.net^
      - ||myhomescreen.tv^
      - @@||mhc-ajax-eu.myhomescreen.tv^
      - @@||mhc-ajax-eu-s2.myhomescreen.tv^

### LINKED ISSUE #112: Addidion for Samsung tv (block the adds on the menu bar)
This will block the adds on the menu bar.
`tvx.adgrx.com`

Tested with RU8000 (aka RU8005).

#Ref. https://eu.community.samsung.com/t5/tv/smart-tv-ads-on-the-menu-bar/td-p/935573/page/16

### LINKED ISSUE #117: Auto Date & Time breaks on LG Smart TV after cold boot / restart
If you unplug the switch or turn off tv automatically.
The LG TV when it boots again makes a connection request to 
`us.lgtvsdp.com` address where it gets its latest date and time or else resets to December 31st 2019.

If it doesn't has the latest time it would have issues with server certificates - 
Apps: 
- Plex says network unreachable
- HBO Max (shows the proper error of the date & time being set behind the current time range server accepts the certificates to generate & make the appropriate handshake)
- Youtube just reloads its boot animation.

I observed that LG TV makes connection request at the first boot 2 times with 30 - 45 secs interval.

By whitelisting this address `us.lgtvsdp.com` and cold booting / switching off the tv completely - unplug the power. Makes it loose the temporary date and time so it makes the request to that connection for latest date and time.
Screen Shot 2021-11-30 at 5 16 04 PM

### PR DESCRIPTION
**Pull request by DandelionSprout**
* Fix #108 
* Fix #109 
* Fix #112 
* Fix #117 
* Addresses the comment at https://github.com/Perflyst/PiHoleBlocklist/issues/82#issuecomment-950193564

@Perflyst

### CODE REVIEW

**Comment by iam-py-test** [comment]
@DandelionSprout do you think #120 should be merged with this request as to avoid merge conflicts

**Comment by DandelionSprout** [comment]
In my eyes, merge conflicts are pretty easy to resolve, so I vote on keeping them separate for now.

**Comment by iam-py-test** [comment]
@DandelionSprout might want to edit the OP to add #109

**Comment by Perflyst** [comment]
You rock! Thanks

**Pull request merged**
