### PR TITLE
Update SmartTV.txt

### PR DESCRIPTION
**Pull request by realErtugrul**
Added cdn.samsungcloudsolution.com

### CODE REVIEW

**Comment by Perflyst** [comment]
This domain is required for system update check on Samsung UE40F5500

**Comment by realErtugrul** [comment]
That's true, tested it in my TV. But the TV is making a query approximately every second. Is this really just for updates?

**Comment by Perflyst** [comment]
I dont know if it is **only** for updates but at least it is required for updates. Less technical users should not face any issues with these blocklists, therefore it is not blocked. Please block it manually in your PiHole if you dont want this connection.

**Comment by realErtugrul** [comment]
That's a good point.

**Pull request closed without merging**
